### ISSUE TITLE
wc-ajax=checkout 500 error caused during checkout

### ISSUE THREAD

**Issue by Shniuras326** [eshoper/woo-lithuaniapost#28]
Getting this error when trying to checkout, even if another shipping method is selected:
```
2023-03-16T22:45:15+00:00 CRITICAL Klaidos žinutė: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woo-lithuaniapost-main/public/class-woo-lithuaniapost-public.php:244
Stack trace:
#0 /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woo-lithuaniapost-main/public/class-woo-lithuaniapost-public.php(244): strpos()
#1 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(308): Woo_Lithuaniapost_Public->validate_selected_terminal()
#2 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1236): do_action()
#5 /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(481): WC_Checkout->process_checkout()
#6 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(308): WC_AJAX::checkout()
#7 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(94): do_action()
#10 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax()
#11 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#12 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /home/uxxxxxxxxx/domains/example.com/public_html/wp-includes/template-loader.php(13): do_action()
#14 /home/uxxxxxxxxx/domains/example.com/public_html/wp-blog-header.php(19): require_once('/home/uxxxxxxxx...')
#15 /home/uxxxxxxxxx/domains/example.com/public_html/index.php(17): require('/home/uxxxxxxx...')
#16 {main}
  thrown (rasta faile /home/uxxxxxxxxx/domains/example.com/public_html/wp-content/plugins/woo-lithuaniapost-main/public/class-woo-lithuaniapost-public.php, eilutės numeris 244)
```
Does not occur with other shipping plugins.

**Comment by eshoper** [comment]
Are you using our newest version of plugin?

**Comment by Shniuras326** [comment]
Yes, using the latest plugin version.

**Comment by eshoper** [comment]
Please contact us pagalba@eshoper.lt

**Comment by Shniuras326** [comment]
Apologies for getting back late. I have managed to resolve the issue by:

1. Deleting the plugin.
2. Re-installing WP core files.
3. Installing the plugin again.

I'm closing the issue since it's working now.
